stages:
  - test
  - deploy

services:
  - mysql:10

variables:
  MYSQL_DATABASE: root
  MYSQL_ROOT_PASSWORD: 123

image: openjdk:13

all-tests:
  stage: test
  script:
    - ./mvnw clean verify -Dspring.profiles.active=pre
  only:
    - develop

pages:
  stage: deploy
  script:
    - ./mvnw generate-resources
    - mkdir .public
    - cp -r target/generated-docs/index.html .public
    - mv .public public
  artifacts:
    paths:
      - public
  only:
    - master

